# Generated by Django 5.0.3 on 2024-03-16 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Finch',
            new_name='finch',
        ),
    ]
